[2024-09-15T18:14:48.292+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_tables manual__2024-09-15T18:14:41.983811+00:00 [queued]>
[2024-09-15T18:14:48.654+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_tables manual__2024-09-15T18:14:41.983811+00:00 [queued]>
[2024-09-15T18:14:48.655+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-15T18:14:48.667+0000] {taskinstance.py:1380} INFO - Executing <Task(PinotTableSubmitOperator): submit_tables> on 2024-09-15 18:14:41.983811+00:00
[2024-09-15T18:14:48.684+0000] {standard_task_runner.py:57} INFO - Started process 11167 to run task
[2024-09-15T18:14:48.693+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_tables', 'manual__2024-09-15T18:14:41.983811+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmp6j_v__n0']
[2024-09-15T18:14:48.696+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask submit_tables
[2024-09-15T18:14:48.940+0000] {task_command.py:415} INFO - Running <TaskInstance: table_dag.submit_tables manual__2024-09-15T18:14:41.983811+00:00 [running]> on host 035d47951d03
[2024-09-15T18:14:49.534+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='codewithyu' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-09-15T18:14:41.983811+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-15T18:14:41.983811+00:00'
[2024-09-15T18:14:50.432+0000] {pinot_table_operator.py:29} INFO - Table successfully submitted to Apache Pinot! /opt/***/dags/tables/customer_dim.json
[2024-09-15T18:14:50.663+0000] {pinot_table_operator.py:31} ERROR - Failed to submit table: 400 - {"code":400,"error":"No content to map due to end-of-input\n at [Source: (String)\"\"; line: 1, column: 0]"}
[2024-09-15T18:14:50.698+0000] {pinot_table_operator.py:35} ERROR - An error occurred: Table submission failed with status code 400
[2024-09-15T18:14:51.199+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_tables, execution_date=20240915T181441, start_date=20240915T181448, end_date=20240915T181451
[2024-09-15T18:14:56.644+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-09-15T18:14:57.410+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
