[2024-09-19T18:13:44.135+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: schema_dag.submit_schemas scheduled__2024-09-16T00:00:00+00:00 [queued]>
[2024-09-19T18:13:46.117+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: schema_dag.submit_schemas scheduled__2024-09-16T00:00:00+00:00 [queued]>
[2024-09-19T18:13:46.377+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-19T18:13:48.509+0000] {taskinstance.py:1380} INFO - Executing <Task(PinotSchemaSubmitOperator): submit_schemas> on 2024-09-16 00:00:00+00:00
[2024-09-19T18:13:49.921+0000] {standard_task_runner.py:57} INFO - Started process 429 to run task
[2024-09-19T18:13:49.979+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'schema_dag', 'submit_schemas', 'scheduled__2024-09-16T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/schema_dag.py', '--cfg-path', '/tmp/tmpcccr51n5']
[2024-09-19T18:13:50.185+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask submit_schemas
[2024-09-19T18:13:53.782+0000] {task_command.py:415} INFO - Running <TaskInstance: schema_dag.submit_schemas scheduled__2024-09-16T00:00:00+00:00 [running]> on host 48913e9acee9
[2024-09-19T18:14:24.966+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='codewithyu' AIRFLOW_CTX_DAG_ID='schema_dag' AIRFLOW_CTX_TASK_ID='submit_schemas' AIRFLOW_CTX_EXECUTION_DATE='2024-09-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-16T00:00:00+00:00'
[2024-09-19T18:14:29.514+0000] {pinot_schema_operator.py:35} ERROR - An error occurred: HTTPConnectionPool(host='pinot-controller', port=9000): Max retries exceeded with url: /schemas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff85a80df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-09-19T18:14:31.714+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=schema_dag, task_id=submit_schemas, execution_date=20240916T000000, start_date=20240919T181344, end_date=20240919T181431
[2024-09-19T18:14:37.974+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-09-19T18:14:44.238+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
